### ISSUE TITLE
Tricky thing with `agent_indicator_v0` in ALE

### ISSUE THREAD

**Issue by vwxyzjn** [Farama-Foundation/SuperSuit#137]
Currently when applying `agent_indicator_v0` with Atari games, `agent_indicator_v0` adds two additional channels of [0, 1] for player 1 and `[1, 0]` for player 2, which looks like below:

![image](https://user-images.githubusercontent.com/5555347/158457918-07d29253-c76e-4fd5-baa9-6e635b50e1b8.png)

```
    env = pong_v2.parallel_env()
    env = ss.color_reduction_v0(env, mode="B")
    env = ss.resize_v0(env, x_size=84, y_size=84)
    # env = ss.frame_stack_v1(env, 4)
    env = ss.agent_indicator_v0(env, type_only=False)
    env = ss.pettingzoo_env_to_vec_env_v1(env)
    envs = ss.concat_vec_envs_v1(env, args.num_envs // 2, num_cpus=0, base_class="gym")
```

This may cause a problem to the learning algorithm because the learning algorithm usually divide the channels by 255, so the agent indicator channels would have looked like [0, 0.0039] and [0.0039, 0] , which is may be not differentiable to the agent. Instead `agent_indicator_v0` should have used the maximum value of the observation space like [255, 0] and [0, 255] as the agent indicator.

**Comment by vwxyzjn** [comment]
@jkterry1

**Comment by benblack769** [comment]
So the problem is making a wrapper that works for a large variety of environments, including vector environments, shaped multi-dimentional observations like [magent](https://www.pettingzoo.ml/magent/battle#observation-space), etc. 

The way this current wrapper deals with these complexities is to utilize the high and low bounds of the Box space. So the pixel observations from the image have a high=255,low=0, and the agent indication observations have a high=1,low=0So if you call

```
env = env.agent_indicator_v0(env)
env = env.normalize(env) # looks at high and low bounds and normalizes to 0-1
```

Should result in both the pixels and the agent indication filling in the full range between 0 and 1.

p.s. I don't necessarily think that the agent_indicator_v0 wrapper is completely optimal, especially for Pettingzoo's multi agent Atari evironments and I recomend using something custom for new experiments.

**Comment by benblack769** [comment]
Another option is to add an argument to the wrapper, something like:

 `env = env.agent_indicator_v0(env, set_value=255)`
