### ISSUE TITLE
Single Atari Preprocessing wrapper?

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/SuperSuit#98]
Would it be possible to have a single wrapper that wraps an Atari environment with all of the standard wrappers?

I know that similar things are implemented in gym (gym.wrappers.atari_preprocessing.AtariPreprocessing) and baselines (baselines.common.atari_wrappers.make_atari and wrap_deepmind)
This would be particularly helpful as you don't need to check that you have all of your wrappers in the correct order etc for replicating prior atari literature

Many thanks

**Comment by jkterry1** [comment]
We had previously planned to implement this feature, @benblack769 would be the one who could do this

**Comment by benblack769** [comment]
We can do this, but it would be single agent only, and it would not support pettingzoo's multi-agent ALE environments. The reason is that there are parts of the default openai ALE environment wrapper that you simply do not want for multiagent. In particular, reset on life loss and reset on no-op. 

Luckily, we do have a reasonably robust framework for giving appropriate errors if a wrapper is applied to the wrong type of environment, so supporting a single-agent only wrapper should not be hard.

**Comment by jkterry1** [comment]
So, there's an additional problem- Atari wrappers are all being moved into the ALE itself in the near future for single agent games. Given this, I think we should close this issue
